- hosts: master, mirror
  become: yes
  tasks:
  - name: Decrypt passwords
    include_vars:
      file: pass.yml

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install RabbitMQ
    package:
      name: rabbitmq-server
      state: present

  - name: Create rabbitmq.conf
    copy:
      content: "loopback_users = none"
      dest: /etc/rabbitmq/rabbitmq.conf

  - name: Create admin user
    rabbitmq_user:
      user: admin
      password: "{{ adminpass }}"
      vhost: /
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      tags: administrator
      state: present

  - name: Delete guest user
    rabbitmq_user:
      user: guest
      state: absent

  - name: Change .erlang.cookie
    copy:
      content: "{{ nodepass }}"
      dest: /var/lib/rabbitmq/.erlang.cookie
      mode: 0400

  - name: Change hosts
    template:
      src: hosts.j2
      dest: /etc/hosts

  - name: Enable management plugin
    command: /usr/sbin/rabbitmq-plugins enable rabbitmq_management

  - name: Restart rabbitmq
    service:
      name: rabbitmq-server
      state: restarted

  - name: Set policy
    rabbitmq_policy:
      name: ha-all
      pattern: .*
      tags:
        ha-mode: all
        ha-sync-mode: automatic

- hosts: mirror
  become: yes
  tasks:
  - name: Create cluster
    shell:
      cmd: /usr/sbin/rabbitmqctl stop_app && /usr/sbin/rabbitmqctl join_cluster "rabbit@{{ groups['master'][0] }}" && /usr/sbin/rabbitmqctl start_app
      warn: no
